FIELD_MAPPING = {
    "get_customer_api": {
        "customerStatus": "customerStatus",
        "idNo": "personalInfo[0].identification[0].idNo",  
        "idType": "personalInfo[0].identification[0].type.code",
        "addressLine1": "contact.address[0].addressLine1",
        "addressLine2": "contact.address[0].addressLine2",
        "addressLine3": "contact.address[0].addressLine3",
        "Postcode": "contact.address[0].postCode",
        "city": "contact.address[0].city",
        "state": "contact.address[0].state.code",
        "countryCode": "contact.address[0].country.code",
    },
    "get_subscriber_api": {
        "customerStatus": ["customerStatus"],
        "telco": ["telco"],
        "activeDate": ["activeDate"],
        "payType": ["payType"],
        "isPrincipal": ["isPrincipal"],
        "status": ["status"],
        "subscriptionName": ["subscriptionName"],
        "customerType": ["customerType"],
        "subscriberType": ["subscriberType"],
        "telecomType": ["telecomType"],
        "tenure": ["tenure"],
    },
    "get_account_structure_api": {
        "customerStatus": ["customerStatus"],
        "accountId": ["accountId"],
        "billingCycle": ["billingCycle"],
    },
    "get_contract_api": {
        "customerStatus": ["customerStatus"],
        "msisdn": ["msisdn"],
        "telco": ["telco"],
        "productType": ["productType"],
        "productName": ["productName"],
        "startDate": ["startDate"],
        "status": ["status"],
    },
}