FIELD_MAPPING = {
    "get_customer_api": {
        "customerStatus": ["customerStatus"],
        "idNo": ["idNo"],
        "idType": ["idType"],
        "addressLine1": ["addressLine1"],
        "addressLine2": ["addressLine2"],
        "addressLine3": ["addressLine3"],
        "Postcode": ["Postcode"],
        "city": ["city"],
        "state": ["state"],
        "countryCode": ["countryCode"],
    },
    "get_subscriber_api": {
        "customerStatus": ["customerStatus"],
        "telco": ["telco"],
        "activeDate": ["activeDate"],
        "payType": ["payType"],
        "isPrincipal": ["isPrincipal"],
        "status": ["status"],
        "subscriptionName": ["subscriptionName"],
        "customerType": ["customerType"],
        "subscriberType": ["subscriberType"],
        "telecomType": ["telecomType"],
        "tenure": ["tenure"],
    },
    "get_account_structure_api": {
        "customerStatus": ["customerStatus"],
        "accountId": ["accountId"],
        "billingCycle": ["billingCycle"],
    },
    "get_contract_api": {
        "customerStatus": ["customerStatus"],
        "msisdn": ["msisdn"],
        "telco": ["telco"],
        "productType": ["productType"],
        "productName": ["productName"],
        "startDate": ["startDate"],
        "status": ["status"],
    },
}