XLSX_FIELD_MAPPING = {
    "get_customer_api": {
        "Status": ["customerStatus"],
        "idType": ["idType"],
        "idNo": ["idNo"],
        "addressLine1": ["addressLine1"],
        "addressLine2": ["addressLine2"],
        "addressLine3": ["addressLine3"],
        "postCode": ["postCode"],
        "city": ["city"],
        "state": ["state"],
        "countryCode": ["countryCode"],
    },
    "get_subscriber_api": {
        "Status": ["subscriberStatus"],
        "telco": ["telco"],
        "iccid": ["iccid"],
        "payType": ["payType"],
        "subscriptionName": ["subscriptionName"],
        "activeDate": ["activeDate"],
        "tenure": ["tenure"],
        "isPrincipal": ["isPrincipal"],
        "status": ["status"],
        "lifeCycleStatus": ["lifeCycleStatus"],
        "customerType": ["customerType"],
        "subscriberType": ["subscriberType"],
        "telecomType": ["telecomType"],
    },
    "get_contract_api": {
        "Status": ["contractStatus"],
        "msisdn": ["msisdn"],
        "telco": ["telco"],
        "productType": ["productType"],
        "productName": ["productName"],
        "startDate": ["startDate"],
        "status": ["status"],
    },
    "get_open_orders_api": {
        "Status": ["openOrderStatus"],
        "msisdn": ["msisdn"],
        "openOrderFlag": ["openOrderFlag"],
        "orderNum": ["orderNumber"],
        "outletId": ["outletId"],
        "orderId": ["orderId"],
        "orderStatus": ["orderStatus"],
    },
    "get_postpaid_validation_api": {
        "Status": ["postpaidValidationStatus"],
        "msisdn": ["msisdn"],
        "custIdType": ["rule_1_result"],
        "ageRange": ["rule_2_result"],
        "hasBlacklist": ["rule_3_result"],
        "upfrontPaymentRequired": ["rule_4_result"],
        "maxLinePerCustomer": ["rule_5_result"],
    },    
    "get_account_structure_api": {
        "Telco": ["telco"],
        "is Principal?": ["msisdn"],
        "num of supp": ["total_supplementary"],
        "account type": ["account_type"],
        "linked principal": ["linked_principal_msisdn"],
        "account_number": ["account_number"],
        "msisdn": ["msisdn"],
        "name": ["customer_name"],
        "payType": ["pay_type"],
        "status": ["status"],
    },
    "account_structure_api_v1": {
        "Principal MSISDN": ["accounts", "principal_msisdn"],
        "Total Supplementary": ["accounts", "total_supp_lines"], 
        "Supplementary MSISDN": ["accounts", "supplementary_msisdn"],
        "Is Original": ["accounts", "is_original_msisdn"]
    },
    "get_family_group_api": {
        "Status": ["customerStatus"],
        "msisdn": ["msisdn"],
        "telco": ["telco"],
        "familyGroupId": ["familyGroupId"],
        "totalFamilyMember": ["totalFamilyMember"],
        "familyGroupLevel": ["familyGroupLevel"],
    }
}