name: API Project CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Verify Python Version
        run: python --version

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel
          pip install -r requirements.txt
          pip install -e .
          
      - name: Create .env file
        run: |
          echo "ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}" >> .env
          echo "ACCESS_TOKEN_EXPIRY_TIME=${{ secrets.ACCESS_TOKEN_EXPIRY_TIME }}" >> .env
          echo "AUTH_TOKEN_URL=${{ secrets.AUTH_TOKEN_URL }}" >> .env
          echo "AUTH_CLIENT_ID=${{ secrets.AUTH_CLIENT_ID }}" >> .env
          echo "AUTH_CLIENT_SECRET=${{ secrets.AUTH_CLIENT_SECRET }}" >> .env
          echo "ACCOUNT_BASE_URL=${{ secrets.ACCOUNT_BASE_URL }}" >> .env
          echo "MOLI_BASE_URL=${{ secrets.MOLI_BASE_URL }}" >> .env

      - name: Restrict Permissions on .env File
        run: chmod 600 .env

      - name: Run Main Scripts (Generate Reports)
        run: |
          source venv/bin/activate
          python run_all_api.py > /dev/null 2>&1

      - name: Email Reports
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          SMTP_SERVER: smtp.gmail.com
          SMTP_PORT: 465
        run: |
          source venv/bin/activate
          python utils/email_reports.py
